edition = "2021"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
newline_style = "Unix"
reorder_imports = true
wrap_comments = true
group_imports = "One"
